services:
  - type: web
    name: abit-fice-api
    runtime: node
    plan: free
    rootDir: apps/api
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: MONGO_URI
        sync: false
      - key: CRON_SECRET
        sync: false
      - key: OFFER_IDS
        value: 1586544,1639860,1591057,1588416,1630258,1586573,1600953,1671590,1601038,1613137,1600952,1588884

  - type: web
    name: abit-fice
    runtime: static
    rootDir: apps/web
    buildCommand: npm ci && npm run build
    staticPublishPath: out
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NEXT_PUBLIC_API_URL
        value: https://abit-fice-api.onrender.com
      - key: NEXT_PUBLIC_OFFER_IDS
        value: 1586544,1639860,1591057,1588416,1630258,1586573,1600953,1671590,1601038,1613137,1600952,1588884
